# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "aj-cloudsentrics-tfstate-323843735194"
    encrypt      = true
    key          = "member-account/terraform.tfstate"
    region       = "us-east-1"
    use_lockfile = true
  }
}
