version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: /terraform/security-tooling
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: /terraform/member-account
    schedule:
      interval: monthly
